use_frameworks!

target 'Annotations_Example' do
  pod 'Annotations', :path => '../'
  pod 'TextAnnotation', :git => 'https://github.com/ulian-onua/TextAnnotation'
  #pod 'TextAnnotation', :path => '../../TextAnnotation'

end

target 'Annotations_Tests' do
  pod 'Annotations', :path => '../'
  pod 'TextAnnotation', :git => 'https://github.com/ulian-onua/TextAnnotation'
 # pod 'TextAnnotation', :path => '../../TextAnnotation'
end
